import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { BOT, REPOSITORY, client, repoPath, pages, number, event, summary, preview, prose, exactKeys, list, oneOutput, noop } from './github.mjs';
const CONTEXT = '/tmp/gh-aw/hypit-review';
const marker = sha => `<!-- hypit-pr-review:${sha} -->`;

export function rightLines(patch) {
  const lines = new Set();
  let right;
  for (const line of (patch ?? '').split('\n')) {
    const hunk = line.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
    if (hunk) right = Number(hunk[1]);
    else if (right !== undefined && /^[ +]/.test(line)) lines.add(right++);
  }
  return lines;
}

export async function prepareReview(api, data) {
  const n = number(data.pull_request?.number ?? data.inputs?.pr_number);
  const pr = await api('GET', repoPath(`pulls/${n}`));
  if (pr.state !== 'open' || pr.draft || pr.labels.some(l => l.name === 'bot-paused')) return { skip: 'PR is closed, draft or paused' };
  if (pr.base.repo.full_name !== REPOSITORY) throw new Error('Unexpected PR base');
  const reviews = await pages(api, repoPath(`pulls/${n}/reviews`));
  if (reviews.some(r => r.user?.login === BOT && r.user.type === 'Bot' && r.body?.startsWith(marker(pr.head.sha)))) return { skip: 'Head commit already reviewed' };
  const files = await pages(api, repoPath(`pulls/${n}/files`));
  const selected = [];
  let budget = 120_000;
  for (const f of files) {
    if (!f.patch || f.status === 'removed' || /(?:\.lock\.yml|pnpm-lock\.yaml|package-lock\.json)$/.test(f.filename)) continue;
    if (selected.length >= 50 || f.patch.length > budget) continue;
    selected.push({ path: f.filename, status: f.status, patch: f.patch });
    budget -= f.patch.length;
  }
  return { repository: REPOSITORY, number: n, head: pr.head.sha, base: pr.base.sha,
    title: pr.title, body: (pr.body ?? '').slice(0, 8000), files: selected,
    total_files: files.length, omitted_files: files.length - selected.length };
}

export function validateReview(report, context) {
  exactKeys(report, ['summary', 'language', 'findings']);
  prose(report.summary);
  if (!['en', 'zh'].includes(report.language)) throw new Error('Invalid language');
  const seen = new Set();
  list(report.findings, 5).forEach(f => {
    exactKeys(f, ['path', 'line', 'severity', 'title', 'detail']);
    const file = context.files.find(file => file.path === f.path);
    if (!file || !Number.isInteger(f.line) || !rightLines(file.patch).has(f.line)) throw new Error('Finding is outside the reviewed diff');
    if (!['P1', 'P2'].includes(f.severity)) throw new Error('Invalid severity');
    if (seen.has(`${f.path}:${f.line}`)) throw new Error('Duplicate finding');
    seen.add(`${f.path}:${f.line}`);
    prose(f.title, 120); prose(f.detail, 900);
  });
  return report;
}

export async function applyReview(api, context, raw, dry = false) {
  if (context.repository !== REPOSITORY || !/^[a-f0-9]{40}$/.test(context.head) || !/^[a-f0-9]{40}$/.test(context.base)) throw new Error('Invalid review context');
  const n = number(context.number);
  const report = validateReview(raw, context);
  const pr = await api('GET', repoPath(`pulls/${n}`));
  if (pr.state !== 'open' || pr.draft || pr.head.sha !== context.head || pr.base.sha !== context.base || pr.labels.some(l => l.name === 'bot-paused')) return { skipped: 'PR changed during review' };
  const reviews = await pages(api, repoPath(`pulls/${n}/reviews`));
  if (reviews.some(r => r.user?.login === BOT && r.user.type === 'Bot' && r.body?.startsWith(marker(context.head)))) return { skipped: 'Head commit already reviewed' };
  const zh = report.language === 'zh';
  const body = [marker(context.head), zh ? '**Hypit AI 代码审查**' : '**Hypit AI code review**', '', prose(report.summary), '',
    zh ? `已检查 ${context.files.length}/${context.total_files} 个文件的可用 diff；未运行代码或测试。` : `Inspected available diffs for ${context.files.length}/${context.total_files} files; code and tests were not executed.`,
    report.findings.length ? '' : (zh ? '在已检查范围内未发现有充分证据的问题；这不代表已批准合并。' : 'No substantiated findings in the inspected scope; this is not an approval.'),
    zh ? '由 DeepSeek 生成，仅供维护者参考。' : 'Generated by DeepSeek for maintainer review.'].filter(Boolean).join('\n\n');
  const payload = { commit_id: context.head, event: 'COMMENT', body,
    comments: report.findings.map(f => ({ path: f.path, line: f.line, side: 'RIGHT', body: `**[${f.severity}] ${prose(f.title, 120)}**\n\n${prose(f.detail, 900)}` })) };
  if (dry) return { preview: { number: n, ...payload } };
  await api('POST', repoPath(`pulls/${n}/reviews`), payload);
  return { reviewed: n, commit: context.head, findings: report.findings.length };
}

async function main() {
  const api = client(), data = event();
  if (process.argv[2] === 'prepare') {
    const context = await prepareReview(api, data);
    mkdirSync(CONTEXT, { recursive: true });
    writeFileSync(`${CONTEXT}/context.json`, JSON.stringify(context));
    if (context.skip) noop(context.skip);
  } else if (process.argv[2] === 'apply') {
    summary(JSON.stringify(await applyReview(api, JSON.parse(readFileSync(`${CONTEXT}/context.json`, 'utf8')), oneOutput(process.env.GH_AW_AGENT_OUTPUT, 'apply_review'), preview(data)), null, 2));
  } else throw new Error('Expected prepare or apply');
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main().catch(e => { console.error(e.message); process.exitCode = 1; });
